### ISSUE TITLE
Cannot select `filepath` as desired capability attribute type in GUI

### ISSUE THREAD

**Issue by kormie** [appium/appium-desktop#1699]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Getting `c is not a function` when selecting `filepath` as the attribute type for the `app` desired capability. The stacktrace points to react code.

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Which version of Appium Desktop?
It is a possible duplicate of https://github.com/appium/appium-desktop/pull/1521, then over https://github.com/appium/appium-desktop/releases/tag/v1.18.0-2 has the fix.

**Comment by kormie** [comment]
App version is: 1.19.1

**Comment by KazuCocoa** [comment]
Thanks.

Could you try with the latest version after removing the AD from your environment once?

When I just open the file icon in the below screenshot, the file selection worked on my environment with AD 1.19 and 1.20.2.
I wondered something condition existed to reprecate your error.
![image](https://user-images.githubusercontent.com/5511591/110042423-1ae2e100-7d89-11eb-927b-3626b4b590b9.png)
